### PR TITLE
added real data to grant show page, refactored basically everything

### PR DESCRIPTION
**Pull request by kenschnarrs**
please test before merging

### CODE REVIEW

**Review by cdrumfelt — DISMISSED** [review]
pushed adjustments to branch, once made then we can merge

**Review by CodesGalore — APPROVED** [review]
Everything looks good and is functional now.

**Review by CodesGalore — APPROVED** [review]
Everything looks good and is functional now.

**Review by CodesGalore — APPROVED** [review]

**Review by CodesGalore — APPROVED** [review]
Everything looks good and is functional now.

**Pull request merged**
